bundles:
- addonChannel: beta
  image: registry-proxy.engineering.redhat.com/rh-osbs/rhacm2-acm-operator-bundle:v2.7.6-4
  dash: 4
  operator: advanced-cluster-management
  version: 2.7.6
  addon: 3.7.6
- addonChannel: beta
  image: registry-proxy.engineering.redhat.com/rh-osbs/multicluster-engine-mce-operator-bundle:v2.2.6-2
  dash: 4
  operator: multicluster-engine
  parent: advanced-cluster-management
  version: 2.2.6
  addon: 3.7.6
